name: Run Unity PlayMode Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playmode-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Unity packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/unity3d
            ~/.local/share/unity3d
          key: ${{ runner.os }}-unity-${{ hashFiles('**/Packages/manifest.json') }}

      - name: Setup Unity
        uses: game-ci/unity-actions/setup@main
        with:
          unityVersion: 2022.3.0f1

      - name: Run PlayMode tests
        uses: game-ci/unity-actions/test@main
        with:
          testMode: playmode

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: PlayMode Test Results
          path: TestResults
